name: CI workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: python:3.9-slim

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        runafter: Checkout
        run: |
          python -m pip install --upgrade pip
          pip install -r config/requirements.txt
      - name: Lint with flake8
        run: |
          flake8 src/app.py --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 src/app.py --count --max-complexity=10 --max-line-length=127 --statistics
      - name: Run unit tests with nose
        run:
          nosetests -v --with-spec --spec-color --with-coverage --cover-package=app
