name: CI workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: python:3.9-slim

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r config/requirements.txt

#      - name: Lint with flake8
#        run: |
#          flake8 src/app.py --count --select=E9,F63,F7,F82 --show-source --statistics
#          flake8 src/app.py --count --max-complexity=10 --max-line-length=127 --statistics

#      - name: Run unit tests with nose
#        run:
#          nosetests -v --with-spec --spec-color --with-coverage --cover-package=app
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker Image
        run: |
          pip install docker
          docker build -t my-flask-app ./config/.
            - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: your-dockerhub-username/your-repo-name:latest


